web_app/routes/__init__.py
from flask import Blueprint, render_template, current_app, redirect, url_for
from web_app.forms import Client_Form_Index
import smtplib
from web_app.routes.listings import listings_bp
from web_app.routes.resources import resources_bp
from web_app.routes.about_us import about_us_bp
from web_app.routes.faculty import faculty_bp


# -------------- INDEX BLUEPRINT ------------------

index_bp = Blueprint(
    'index',
    __name__,
    template_folder='templates',
    static_folder='static'
)


# INDEX ROUTE

@index_bp.route("/", methods=["GET", "POST"])
def index():
    client_form : Client_Form_Index = Client_Form_Index()
    

    if client_form.validate_on_submit():
        sender: str = current_app.config['EMAIL']
        pswrd: str = current_app.config['PSWRD']
        port: int = current_app.config['PORT']
        print(sender, pswrd, port)
        host = "smtp.gmail.com"
        subject = f" Client, {client_form.name.data} form submission."
        body = f'''

        ** CLIENT CONTACT INFO BELOW **

        Client information:

        name : {client_form.name.data}

        email : {client_form.email.data}

        cell : {client_form.cell_number.data}

        website: {client_form.website_address.data}

        annual revenue : {client_form.annual_revenue.data}

        questions or comments : \n {client_form.questions_or_comments.data} \n



        ** MUST ADD BUSINESS INFO BELOW THROUGH ROOT ACC ASAP **

        business information:

        business name: {client_form.business_name.data}
        '''
        message = f''' From: {sender}
        
        Subject: {subject}\n
        {body}
        '''

        try:
            server = smtplib.SMTP(host, port)
            server.starttls()
            server.login(sender, pswrd )
            server.sendmail(
                sender,
                sender,
                message
            )
            server.close()
        except:
            print("Mail failed to send.")
        
        return redirect(url_for('.index')) # SUCCESS MESSAGE NEEDED

    return render_template("index.html", client_form=client_form)

web_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A Mid-Market M&A Consulting Agency | Cochran Consulting LLC</title>
    <!-- overall css -->
    <link rel="icon" type="png" href="/static/images/ccllc_logo.png" sizes="52x52">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css' ) }}"/> 
    <link rel="stylesheet" href="{{ url_for('static', filename='css/body/body.css') }}"/>

    <!-- header CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/body/header/company.css') }}"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/body/header/navigation.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/body/header/socials.css') }}">

    <!-- MAIN CSS BLOCK -->  
    {% block head %}
    {% endblock %}

    <!-- footer CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/body/footer/footer-info.css') }}">

    <!-- google and font awsome font links -->
    <link 
      href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"
    />
    <link 
    rel="stylesheet" 
    href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"
    />


    


</head>
<body>
    <header>
        <section id="company">
            <a class="header-left__anchor" href="{{ url_for('index.index') }}">
            <img id="logo" src="{{ url_for('static', filename='images/ccllc_logo.png') }}" alt="Cochran Consulting LLC logo"/>
            </a>
            <section id="sub-name"><h1>Cochran </h1><p id="subtitle">Consulting, llc</p></section>
        </section>
        <section>

            <nav id="navigation-bar">
                <div class="dropdown hide" data-dropdown>
                    <button class="link" data-dropdown-button>About Us</button>
                    <div class="dropdown-menu">
                        <ul>
                            <li><a href="{{ url_for('about_us.our_team') }}">Our Team</a></li>
                            <li><a href="{{ url_for('about_us.our_company_mindset') }}">Our Company Mindest</a></li>
                        </ul>
                    </div>
                </div>

                <div class="dropdown hide" data-dropdown>
                    <button class="link" data-dropdown-button>Listings</button>
                    <div class="dropdown-menu">
                        <ul>
                            <li><a href="{{ url_for('listings.business_listings') }}">Business Listings</a></li>
                            <li><a href="{{ url_for('listings.real_estate_listings') }}">Real Estate Listings</a></li>
                        </ul>
                    </div>
                </div>

                <div class="dropdown hide" data-dropdown>
                    <button class="link" data-dropdown-button>Resources</button>
                    <div class="dropdown-menu">
                        <ul>
                            <li><a href="{{ url_for('resources.z_score') }}">Z-Score</a></li>
                            <li><a href="{{ url_for('resources.our_nprfts') }}">Our Non-Profits</a></li>
                            <li><a href="{{ url_for('resources.our_books') }}">Our Books</a></li>
                        </ul>
                    </div>
                </div>

                <div class="dropdown hide" data-dropdown>
                    <button class="link" data-dropdown-button>Faculty</button>
                    <div class="dropdown-menu">
                        <ul>
                            {% if not session['email'] %}
                            <li><a href="{{ url_for('faculty.login') }}">Employee Login</a></li>
                            {% endif %}

                            {% if session['email'] %}
                            <li><a href="{{ url_for('faculty.add_or_edit') }}">Add Or Edit</a></li>
                            <li><a href="{{ url_for('faculty.logout') }}">Logout</a></li>
                            {% endif %}

                        </ul>
                    </div>
                </div>

<!-- ------------------------------------ bar menu ----------------------------------------- -->
                
                <div class="dropdown" data-dropdown id="bar" >
                    <button class="link material-symbols-outlined resize" data-dropdown-button>menu</button>

                        <div class="dropdown-menu bars">
                            <ul>
                                <li>
                                    <div class="dropdown-2" data-dropdown-2>
                                    <button class="link inner" data-dropdown-button-2>About Us</button>
                                    <div class="dropdown-menu two">
                                        <ul>
                                            <li><a href="{{ url_for('about_us.our_team') }}">Our Team</a></li>
                                            <li><a href="{{ url_for('about_us.our_company_mindset') }}">Our Company Mindest</a></li>
                                            
                                        </ul>
                                    </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="dropdown-2" data-dropdown-2>
                                    <button class="link inner" data-dropdown-button-2>Listings</button>
                                    <div class="dropdown-menu two">
                                        <ul>
                                            <li><a href="{{ url_for('listings.business_listings') }}">Business Listings</a></li>
                                            <li><a href="{{ url_for('listings.real_estate_listings') }}">Real Estate Listings</a></li>
                                        </ul>
                                    </div>
                                    </div>
                                </li>
                                <li>
                                    <div class="dropdown-2" data-dropdown-2>
                                    <button class="link inner" data-dropdown-button-2>Resources</button>
                                    <div class="dropdown-menu two">
                                        <ul>
                                            <li><a href="{{ url_for('resources.z_score') }}">Z-Score</a></li>
                                            <li><a href="{{ url_for('resources.our_nprfts') }}">Our Non-Profits</a></li>
                                            <li><a href="{{ url_for('resources.our_books') }}">Our Books</a></li>
                                        </ul>
                                    </div>
                                    </div>
                                </li>
                                <li>


                                    <div class="dropdown-2" data-dropdown-2>
                                        <button class="link inner" data-dropdown-button-2>Faculty</button>
                                        <div class="dropdown-menu two">
                                            <ul>
                                                {% if not session['email'] %}
                                                <li><a href="{{ url_for('faculty.login') }}">Employee Login</a></li>
                                                {% endif %}
                    
                                                {% if session['email'] %}
                                                <li><a href="{{ url_for('faculty.add_or_edit') }}">Add Or Edit</a></li>
                                                <li><a href="{{ url_for('faculty.logout') }}">Logout</a></li>
                                                {% endif %}
                    
                                            </ul>
                                        </div>
                                        </div>



                                </li>
                            </ul>
                    </div>
                </div>
                

            </nav>
        </section>
        <section>
        <ul id="socials">
            <li>
            <a href="https://www.facebook.com/ccochranconsulting" target="_blank">
                    <i class="fab fa-facebook-f f icon"></i>
                </a>
            </li>
            <li>
                <a href="https://www.instagram.com/ccochranconsulting/" target="_blank">
                    <i class="fab fa-instagram i icon"></i>
                </a>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/ccochranconsulting" target="_blank">
                    <i class="fab fa-linkedin-in l icon"></i>
                </a>
            </li>
            <li>
                <a href="https://www.youtube.com/@dr.curtisc.cochran8797" target="_blank">
                    <i class="fab fa-youtube y icon"></i>
                </a>
            </li>
            <li>
                <a href="https://www.amazon.com/s?i=digital-text&rh=p_27%3ADr.+Curtis++C.+Cochran+&s=relevancerank&text=Dr.+Curtis++C.+Cochran+&ref=dp_byline_sr_ebooks_1" target="_blank">
                    <i class="fab fa-amazon a icon"></i>
                </a>
            </li>
        </ul>
        </section>
    </header>
    

        {% block main_content %}
        {% endblock %}

    
    
    <footer>
        <article>
            <a href="mailto:curtis@ccochranconsulting.com">
                <i class="material-icons">email</i>
                <span>curtis@ccochranconsulting.com</span>
            </a>
        </article>
        <article>
            <a href="https://www.google.com/maps/place/5198+Arlington+Ave+Suite+%23617,+Riverside,+CA+92504/@33.9446269,-117.415647,17z/data=!3m1!4b1!4m6!3m5!1s0x80dcb103cbfe7829:0x62172adb09f916a4!8m2!3d33.9446269!4d-117.415647!16s%2Fg%2F11rnf9wf6v" target="_blank">
                <i class="material-icons">place</i>
                <span>5198 Arlington Avenue Suite #617 Riverside, CA 92504</span>
            </a>  
        </article>
        <article>
            <a href="tel:19512377234">
                <i class="material-icons">phone</i>
                <span>951.237.7234</span>
            </a>
        </article>
    </footer>

    

    
    <script src="{{ url_for('static', filename='scripts/navDropDownMenus.js') }}"></script>
    {% block scripts %}
    {% endblock %}
    
</body>
</html>

web_app/templates/index.html
{% extends "base.html" %}
{% from "utilities/macros/fields/iter_fields.jinja2" import iter_fields %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/body/main/e-square.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/body/main/form.css') }}">
    <link rel="stylesheet" href=" {{ url_for('static', filename='css/body/main/blockquote.css') }} ">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/body/main/testimonials&businesses.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/body/main/books.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/site_mods/add_or_edit.css') }}">
{% endblock %}

{% block main_content %}
    <main class="main__index">
    <article id="e-square-background">
        <section id="e-square">

            <h2 class="e1-info-title position">Entering</h2>
            <p class="e-info-background" id="e1-background-info">
                Entrepreneurs considering Entering business ownership were previously known as
                buyers. We now refer to them as Entering entrepreneurs because there are many effective
                opportunities to become the owner of a business in addition to buying a business.
            </p>

            <h2 class="e2-info-title position">Evaluating</h2>
            <p class="e-info-background" id="e2-background-info">
                
                A successful Business Enhancement Plan
                is the plan of action that accomplishes the needed objectives indicated in the 
                Evaluation Report. Our Primary Business Consultant will lead in the design of 
                this plan and monitor each step in the accomplishment of increased cash flow.
            </p>

            <h2 class="e3-info-title position">Enhancing</h2>
            <section class="e-info-background" id="e3-background-info">
                <ul id="e3-list">
                    <li>Understand Business Value</li>
                    <li>Present Value of Future Earnings</li>
                    <li>Gross Revenue Multiples</li>
                    <li>Capitalization of Excess Earnings</li>
                    <li>Fair Market Value</li>
                </ul>
            </section>

            <h2 class="e4-info-title position">Exiting</h2>
            <p class="e-info-background" id="e4-background-info">     
                At some point, the owner of every business will consider 
                an Exit Strategy to cash in on years of hard work and investment. 
                If you have a current interest in Exiting your business, or 
                considering maximizing the value of your business for a future 
                Exit, this is an excellent time to make your move.
            </p>

            <div class="e-div e1"><img class="e" src="../static/images/e_square/e1.png" alt="image with e raised 1"></div>
            <div class="e-div e2"><img class="e" src="../static/images/e_square/e2.png" alt="image with e and 2"></div>
            <div class="e-div e3"><img class="e" src="../static/images/e_square/e3.png" alt="image with e and 3"></div>
            <div class="e-div e4"><img class="e" src="../static/images/e_square/e4.png" alt="image with e and 4"></div>               
        </section>

        <section id="e-square-subtext-section">
        <hr class="hr1">
        <p id="first-paragraph">
            Our Consulting and Executive Coaching Firm is a middle market 
            Mergers & Acquisitions Firm specializing in Businesses from 
            $500,000 to $50,000,000 in assets. We serve Entrepreneurs by 
            facilitating the 4 stages of Business Ownership: Entering, Evaluating, 
            Enhancing, and Exiting. Whether you are our Entering or Exiting Client,
            we have a fiduciary duty to you, your family and your business. 
        </p>
        <p> 
            Each step of your business ownership cycle is important. However, the balance that
            comes from the un-compromised coordination of all four steps can bring you
            success. Whether your goal is financial independence when you Exit your
            business or expanding business with profits, this is what we do best.
            Earn more, keep more, we will help you explore your options in all phases
            of business ownership.  
        </p>
        <hr class="hr2">
    </section>
    </article>
    <article id="form">
        <h2 id="form-title">TALK TO AN EXPERT</h2>
        <section id="who">
            
            <figure id="frame">
                <img id="cochran" src="../static/images/cc-ceo.png" 
                alt="image of a man named Dr.Cochran">
                <figcaption>Dr. Cochran, PH.D, MBA</figcaption>
            </figure>
            <p id="business-info">Only companies with annual revenues of $500,000 to 
                $50 Million, please. Call Dr. Curtis Cochran, CEO & President 
                951.237.7234 or complete the form below.
            </p>
        </section>
        <section id="fill-in">
            <!-- must get database to store form "fill-in" information -->
            <form class="client__form" action="" method="post">
                {{ iter_fields(client_form) }}
            </form>
        </section>
    </article>
    <blockquote id="blockquote">
        <hr class="quote-hr">
        <p id="quote">
            "Plan ahead for success when Exiting your 
            business, or plan for less than what you 
            hoped for. Only the best prepared businesses 
            will sell for top dollar."
        </p>
        <hr class="quote-hr">
      </blockquote>
    <section id="reviews-and-sold-background">
        <article id="testimonials-article">
            <h2 id="testimonials-title">Testimonials</h2>
            <ul id="testimonials">
                <li class="testimonial">
                    "He knows what he is doing with these transactions."
                    - <mark>Trent Westermeyer, BEST Realty Property Management, Inc.</mark>
                </li>
                <li class="testimonial">
                    "A true exit strategy expert. I can't 
                    recommend Curtis highly enough."
                    - <mark>Chris Curtin, Bankers Factoring</mark>

                </li>
                <li class="testimonial">
                    "Cochran Consulting helped us Enter 
                    business ownership and Enhance our business. 
                    We highly recommend their services!"
                    - <mark>Nature's Healing LLC</mark>
                </li>
                <li class="testimonial">
                    "I have known him since he was a teacher in high 
                    school and he provides great consulting advice for your business." 
                    - <mark>Michelle McDonnel IE Magazine</mark>
                </li>
            </ul>
        </article>
        <article id="businesses-article">
            <h2 id="sold-title">Businesses Sold</h2>
            <ul id="businesses">
                <li class="business">Solar Sales & Installation Company</li>
                <li class="business">Fence Contractor</li>
                <li class="business">Food Truck Business</li>
                <li class="business">Turnkey Donut Shop</li>
                <li class="business">Established Auto Repair</li>
            </ul>
        </article>
    </section>
    <article id="books-background">
        <h2 id="books-title">Our Books</h2>
        <figure class="figures">
            <img id="book-1" src="{{ url_for('static', filename='images/books/cc-book-1.png') }}" alt="The Semantics of Mathematics book image">
            <div class="overlay">
                <a href="https://www.amazon.com/Semantics-Mathematics-Business-Curtis-Cochran-ebook/dp/B08P659PYZ/ref=sr_1_3?keywords=dr+curtis+cochran&sr=8-3" target="_blank"><div class="text">Purchase</div></a>
            </div>
        </figure>
        <figure class="figures">
            <img id="book-2" src="{{ url_for('static', filename='images/books/cc-book-2.png') }}" alt="Metaphysics in Business book image">
            <div class="overlay">
                <a href="https://www.amazon.com/Metaphysics-Business-Dr-Curtis-Cochran-ebook/dp/B01NASNX52/ref=sr_1_1?keywords=dr+curtis+cochran&sr=8-1" target="_blank"><div class="text">Purchase</div></a>
            </div>
        </figure>
        <figure class="figures">
            <img id="book-3" class="smaller-book" src="{{ url_for('static', filename='images/books/cc-book-3.png') }}" alt="Mathematics and the Metaphysical regression of Human Knowledge book image">
            <div class="overlay">
                <a href="https://www.amazon.com/MATHEMATICS-METAPHYSICAL-REGRESSION-HUMAN-KNOWLEDGE-ebook/dp/B06XJX7FFD/ref=sr_1_7?keywords=dr+curtis+cochran&sr=8-7" target="_blank"><div class="text">Purchase</div></a>
            </div>
        </figure>
        <figure class="figures">
            <img id="book-4" src="{{ url_for('static', filename='images/books/cc-book-4.png') }}" alt="Reaching Wealth book image">
            <div class="overlay">
                <a href="https://www.amazon.com/Reaching-Wealth-Through-Executive-Coaching-ebook/dp/B0B5PM6489/ref=sr_1_2?keywords=Dr+curtis+c+cochran&sr=8-2" target="_blank"><div class="text">Purchase</div></a>
            </div>
        </figure>
    </article>
</main>

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='scripts/eSquare.js') }}"></script>
{% endblock %}